/// Flutter icons List_fooddart
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  List_fooddart
///      fonts:
///       - asset: fonts/List_fooddart.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class List_fooddart {
  List_fooddart._();

  static const _kFontFam = 'List_fooddart';

  static const IconData food = IconData(0xe800, fontFamily: _kFontFam);
}
